image: java:latest

build:
    stage: build
    script: 
        - echo "Building"
        - java -version
        - javac -cp "src/lib/*" src/uk/ac/gla/dcs/tp3_2019_ese1/*/*.java

test:
  stage: test
  script: 
        - echo "Testing"
#       - java src/uk/ac/gla/dcs/tp3_2019_ese1/test/Test

