image: java:latest

build:
    stage: build
    script: 
        - echo "Building"
        - java -version
        - mkdir bin 
        - javac -cp "lib/*" -d bin -sourcepath src src/uk/ac/gla/dcs/tp3_2019_ese1/*/*.java

test:
  stage: test
  script: 
        - echo "Testing"
        - javac -cp "lib/*" -d bin -sourcepath src src/uk/ac/gla/dcs/tp3_2019_ese1/test/Test.java 
        - java -cp "bin:lib/*" uk/ac/gla/dcs/tp3_2019_ese1/test/Test
        #- javac src/uk/ac/gla/dcs/tp3_2019_ese1/test/Test
        #- java src/uk/ac/gla/dcs/tp3_2019_ese1/test/Test


