image: java:latest

build:
    stage: build
    script: 
        - echo "Building"
        - java -version
        - mkdir bin
        - javac --enable-preview -cp "lib/*" -d bin $(find ./src/* | grep .java)

test:
  stage: test
  script: 
        - echo "Testing"
        #- javac src/uk/ac/gla/dcs/tp3_2019_ese1/test/Test
        #- java src/uk/ac/gla/dcs/tp3_2019_ese1/test/Test

